version: "3"
services:
    whatsapp-chatgpt:
        image: ghcr.io/askrella/whatsapp-chatgpt:master
        environment:
            OPENAI_API_KEY: "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"
            OPENAI_GPT_MODEL: ""
            PREFIX_ENABLED: ""
            SERPAPI_API_KEY: ""
        volumes:
            - session-data:/app/session
volumes:
    session-data:
